sinks:
  my_sink_id:
    type: humio_logs
    inputs:
      - my-source-or-transform-id
    endpoint: http://localhost:8008
    event_type: json
    host_key: hostname
    source: "{{file}}"
    buffer: null
    batch: null
    compression: none
    encoding: null
    healthcheck: null
    request: null
    tls: null
    proxy: null