version: '3.7'

services:
  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
  humio:
    image: humio/humio
    ports:
      - 8008:8008
    volumes:
      - ./config/humio.yml:/etc/humio/humio.yml
      - ./config/humio.yml:/humio/humio.yml
      - ./humio:/humio
    environment:
      - ./config/humio.yml
    networks:
      - humio_nw
    cap_add:
      - NET_ADMIN
networks:
  monitoring:
  humio_nw: